# WEEK 2 · ACTIVITY 1 OF 4 · LESSON
#
# You will learn:
#   A method can change the data stored on one object.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see Mira's health go from 100 to 70.
#   4. Then open 01_your_turn.py.
#
# Do not edit this file.

class Hero:
    def __init__(self, name):
        self.name = name
        self.health = 100

    def take_damage(self, amount):
        # self.health is this hero's own number.
        # This line changes that number.
        self.health = self.health - amount
        print(f"{self.name} took {amount} damage. Health is now {self.health}.")


mira = Hero("Mira")
print(f"{mira.name} starts with {mira.health} health.")
mira.take_damage(30)

print("---")
print("If you saw health go from 100 to 70, this lesson worked.")
print("Next file: 01_your_turn.py")
