# WEEK 2 · ACTIVITY 2 OF 4 · LESSON
#
# You will learn:
#   A method can take another object and change that object.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see Zed's health go from 100 to 75.
#   4. Then open 02_your_turn.py.
#
# Do not edit this file.

class Hero:
    def __init__(self, name, power):
        self.name = name
        self.health = 100
        self.power = power

    def take_damage(self, amount):
        self.health = self.health - amount

    def attack(self, other):
        # other is a second Hero, not a number.
        # This line changes the other hero's health.
        other.take_damage(self.power)
        print(f"{self.name} hits {other.name} for {self.power} damage.")


mira = Hero("Mira", 25)
zed = Hero("Zed", 10)

print(f"Before the hit, {zed.name} has {zed.health} health.")
mira.attack(zed)
print(f"After the hit, {zed.name} has {zed.health} health.")

print("---")
print("If Zed went from 100 to 75, this lesson worked.")
print("Next file: 02_your_turn.py")
