# WEEK 2 · ACTIVITY 3 OF 4 · LESSON
#
# You will learn:
#   __str__ lets print(hero) show a sentence you choose.
#   The name has two underscores on each side. You do not call it yourself.
#   print() calls it for you.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see: Mira | health: 70
#   4. Then open 03_your_turn.py.
#
# Do not edit this file.

class Hero:
    def __init__(self, name):
        self.name = name
        self.health = 100

    def take_damage(self, amount):
        self.health = self.health - amount

    def __str__(self):
        return f"{self.name} | health: {self.health}"


mira = Hero("Mira")
mira.take_damage(30)
print(mira)

print("---")
print("If you saw: Mira | health: 70")
print("this lesson worked.")
print("Next file: 03_your_turn.py")
