# WEEK 2 · ACTIVITY 4 OF 4 · LESSON
#
# You will learn:
#   A class attribute is one value shared by every object.
#   self.name is different for each hero.
#   Hero.heroes_made is one counter for the whole class.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see the counter go 0, then 1, then 2.
#   4. Then open 04_your_turn.py.
#
# Do not edit this file.

class Hero:
    heroes_made = 0

    def __init__(self, name):
        self.name = name
        Hero.heroes_made = Hero.heroes_made + 1


print("Heroes made:", Hero.heroes_made)

mira = Hero("Mira")
print("After creating", mira.name, "→", Hero.heroes_made)

zed = Hero("Zed")
print("After creating", zed.name, "→", Hero.heroes_made)

print("---")
print("If the counter went 0, then 1, then 2, this lesson worked.")
print("Next file: 04_your_turn.py")
