# WEEK 2 · ACTIVITY 5 · EXTRA
#
# Do this only after activities 1 to 4 print PASSED.
#
# You will learn:
#   One object can keep a list of other objects.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see both hero names under the team name.
#   4. Then open 05_your_turn.py.
#
# Do not edit this file.

class Hero:
    def __init__(self, name):
        self.name = name


class Team:
    def __init__(self, name):
        self.name = name
        self.members = []

    def add_hero(self, hero):
        self.members.append(hero)

    def show(self):
        print("Team", self.name)
        for hero in self.members:
            print("-", hero.name)


team = Team("Night Owls")
team.add_hero(Hero("Mira"))
team.add_hero(Hero("Zed"))
team.show()

print("---")
print("If you saw Mira and Zed listed under Night Owls, this lesson worked.")
print("Next file: 05_your_turn.py")
