# WEEK 4 · ACTIVITY 1 OF 4 · LESSON
#
# You will learn:
#   import math loads square root, rounding, and pi.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see 12.0, then 7, then 8, then a circumference.
#   4. Then open 01_your_turn.py.
#
# Do not edit this file.

import math

print("Square root of 144:", math.sqrt(144))
print("Round 7.9 down:", math.floor(7.9))
print("Round 7.1 up:", math.ceil(7.1))
print("Circumference of radius 5:", 2 * math.pi * 5)

print("---")
print("If you saw 12.0 for the square root, this lesson worked.")
print("Next file: 01_your_turn.py")
