# WEEK 4 · ACTIVITY 2 OF 4 · LESSON
#
# You will learn:
#   random.randint picks a whole number from a range.
#   Both ends count: randint(1, 6) can be 1, 2, 3, 4, 5, or 6.
#   random.choice picks one item from a list.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see a dice number from 1 to 6, then one colour.
#   4. Run it again. The dice number can change. That is correct.
#   5. Then open 02_your_turn.py.
#
# Do not edit this file.

import random

roll = random.randint(1, 6)
print("Dice roll:", roll)

colours = ["red", "green", "blue"]
print("Colour:", random.choice(colours))

print("---")
print("If the dice is from 1 to 6, this lesson worked.")
print("Next file: 02_your_turn.py")
