# WEEK 4 · ACTIVITY 3 OF 4 · LESSON
#
# You will learn:
#   datetime can turn a date into text with strftime.
#   "%Y-%m-%d" means year-month-day, like 2014-03-15.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see today's date, then March 15, 2014 as 2014-03-15.
#   4. Then open 03_your_turn.py.
#
# Do not edit this file.

import datetime

now = datetime.datetime.now()
print("Today:", now.strftime("%Y-%m-%d"))
print("Time:", now.strftime("%H:%M"))

birthday = datetime.date(2014, 3, 15)
print("Birthday:", birthday.strftime("%Y-%m-%d"))

print("---")
print("If the birthday line is 2014-03-15, this lesson worked.")
print("Next file: 03_your_turn.py")
