# WEEK 4 · ACTIVITY 4 OF 4 · LESSON
#
# You will learn:
#   json.dump writes a dict to a file.
#   json.load reads that file back into a dict.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see the saved player, then the name Mira.
#   4. Then open 04_your_turn.py.
#
# Do not edit this file.

import json
import os

player = {"name": "Mira", "score": 40}
path = "week4_demo.json"

with open(path, "w") as file:
    json.dump(player, file)

with open(path, "r") as file:
    loaded = json.load(file)

print("Loaded:", loaded)
print("Name:", loaded["name"])
os.remove(path)

print("---")
print("If the name is Mira, this lesson worked.")
print("Next file: 04_your_turn.py")
