# WEEK 4 · ACTIVITY 5 · EXTRA
#
# Do this only after activities 1 to 4 print PASSED.
#
# You will learn:
#   os.path.exists tells you if a file is there before you open it.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see None for the missing file, then the loaded score.
#   4. Then open 05_your_turn.py.
#
# Do not edit this file.

import json
import os

def load_score(path):
    if not os.path.exists(path):
        return None
    with open(path, "r") as file:
        return json.load(file)


print("Missing file:", load_score("not_a_real_file.json"))

path = "week4_demo.json"
with open(path, "w") as file:
    json.dump({"score": 40}, file)

print("Saved file:", load_score(path))
os.remove(path)

print("---")
print("If you saw None, then a score of 40, this lesson worked.")
print("Next file: 05_your_turn.py")
