# WEEK 3 · ACTIVITY 1 OF 4 · LESSON
#
# You will learn:
#   try / except can stop a bad value from crashing the program.
#   An exception is an error that stops Python.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see 12, then a message about hello, then None.
#   4. Then open 01_your_turn.py.
#
# Do not edit this file.

def safe_int(text):
    try:
        return int(text)
    except ValueError:
        print(text, "is not a whole number.")
        return None


print(safe_int("12"))
print(safe_int("hello"))

print("---")
print("If you saw 12, then a message, then None, this lesson worked.")
print("The program did not crash.")
print("Next file: 01_your_turn.py")
