# WEEK 3 · ACTIVITY 2 OF 4 · LESSON
#
# You will learn:
#   The name after except must match the kind of error.
#   IndexError means that spot is not in the list.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see milk, then None.
#   4. Then open 02_your_turn.py.
#
# Do not edit this file.

def get_item(items, index):
    try:
        return items[index]
    except IndexError:
        print("That spot is not in the list.")
        return None


shopping = ["milk", "eggs", "bread"]
print(get_item(shopping, 0))
print(get_item(shopping, 10))

print("---")
print("If you saw milk, then a message, then None, this lesson worked.")
print("Next file: 02_your_turn.py")
