# WEEK 3 · ACTIVITY 3 OF 4 · LESSON
#
# You will learn:
#   raise creates an error on purpose when a value is not allowed.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see 10 stored, then "Caught:", then scores [10, 8].
#   4. Then open 03_your_turn.py.
#
# Do not edit this file.

class ScoreBook:
    def __init__(self):
        self.scores = []

    def add_score(self, value):
        if value <= 0:
            raise ValueError("Score must be a positive number.")
        self.scores.append(value)
        print("Stored", value)


book = ScoreBook()
book.add_score(10)

try:
    book.add_score(-3)
except ValueError as error:
    # as error saves the message so we can print it
    print("Caught:", error)

book.add_score(8)
print("Scores:", book.scores)

print("---")
print("If -3 was caught and the scores are [10, 8], this lesson worked.")
print("Next file: 03_your_turn.py")
