# WEEK 3 · ACTIVITY 4 OF 4 · LESSON
#
# You will learn:
#   You can make your own error name.
#   InvalidScoreError is an error type you created.
#   pass here means the class needs no extra code. The name is the point.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see "Caught a bad score" and then Scores: [5].
#   4. Then open 04_your_turn.py.
#
# Do not edit this file.

class InvalidScoreError(Exception):
    pass


class ScoreBook:
    def __init__(self):
        self.scores = []

    def add_score(self, value):
        if value <= 0:
            raise InvalidScoreError("Score must be a positive number.")
        self.scores.append(value)


book = ScoreBook()
try:
    book.add_score(0)
except InvalidScoreError as error:
    print("Caught a bad score:", error)

book.add_score(5)
print("Scores:", book.scores)

print("---")
print("If 0 was caught and the only score is 5, this lesson worked.")
print("Next file: 04_your_turn.py")
