# WEEK 3 · ACTIVITY 5 · EXTRA
#
# Do this only after activities 1 to 4 print PASSED.
#
# You will learn:
#   FileNotFoundError happens when you open a file that is not there.
#   except can handle that without a crash.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see None for the missing file, then 40 for the real file.
#   4. Then open 05_your_turn.py.
#
# Do not edit this file.

import os

def read_saved_score(filename):
    try:
        with open(filename, "r") as file:
            return file.read()
    except FileNotFoundError:
        return None


print(read_saved_score("missing_score.txt"))

with open("saved_score.txt", "w") as file:
    file.write("40")

print(read_saved_score("saved_score.txt"))

os.remove("saved_score.txt")

print("---")
print("If you saw None, then 40, this lesson worked.")
print("Next file: 05_your_turn.py")
