# WEEK 5 · ACTIVITY 1 OF 5 · LESSON
#
# You will learn:
#   A Player object keeps a list of scores.
#   best_score returns the biggest one, or 0 when the list is empty.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see best 0, then best 40.
#   4. Then open 01_your_turn.py.
#
# Do not edit this file.

class Player:
    def __init__(self, name):
        self.name = name
        self.scores = []

    def add_score(self, value):
        self.scores.append(value)

    def best_score(self):
        if len(self.scores) == 0:
            return 0
        return max(self.scores)


mira = Player("Mira")
print("Best so far:", mira.best_score())
mira.add_score(10)
mira.add_score(40)
print("Scores:", mira.scores)
print("Best so far:", mira.best_score())

print("---")
print("If the best score changed from 0 to 40, this lesson worked.")
print("Next file: 01_your_turn.py")
