# WEEK 5 · ACTIVITY 2 OF 5 · LESSON
#
# You will learn:
#   add_score raises ValueError when the score is not positive.
#   This is the same raise you used in week 3.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see 20 stored, then "Caught", and scores [20].
#   4. Then open 02_your_turn.py.
#
# Do not edit this file.

class Player:
    def __init__(self, name):
        self.name = name
        self.scores = []

    def add_score(self, value):
        if value <= 0:
            raise ValueError("Score must be a positive number.")
        self.scores.append(value)
        print("Stored", value)


mira = Player("Mira")
mira.add_score(20)
try:
    mira.add_score(-5)
except ValueError as error:
    print("Caught:", error)
print("Scores:", mira.scores)

print("---")
print("If -5 was caught and the only score is 20, this lesson worked.")
print("Next file: 02_your_turn.py")
