# WEEK 5 · ACTIVITY 3 OF 5 · LESSON
#
# You will learn:
#   A score can be a dict with two keys: value and date.
#   The date is text from datetime, like 2026-09-26 15:30.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see one dict, then best score 50.
#   4. Then open 03_your_turn.py.
#
# Do not edit this file.

import datetime

class Player:
    def __init__(self, name):
        self.name = name
        self.scores = []

    def add_score(self, value):
        date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        entry = {"value": value, "date": date}
        self.scores.append(entry)

    def best_score(self):
        if len(self.scores) == 0:
            return 0
        best = self.scores[0]["value"]
        for entry in self.scores:
            if entry["value"] > best:
                best = entry["value"]
        return best


mira = Player("Mira")
mira.add_score(50)
print("Scores:", mira.scores)
print("Best:", mira.best_score())

print("---")
print("If you see a dict with value 50 and today's date, this lesson worked.")
print("Next file: 03_your_turn.py")
