# WEEK 5 · ACTIVITY 4 OF 5 · LESSON
#
# You will learn:
#   json.dump saves the players to a file.
#   json.load reads them back into Player objects.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see Mira's score, 40, after the file is loaded.
#   4. Then open 04_your_turn.py.
#
# Do not edit this file.

import json
import os

class Player:
    def __init__(self, name):
        self.name = name
        self.scores = []

def save_all(path, players):
    data = []
    for player in players.values():
        data.append({"name": player.name, "scores": player.scores})
    with open(path, "w") as file:
        json.dump(data, file, indent=2)

def load_all(path):
    with open(path, "r") as file:
        data = json.load(file)
    players = {}
    for entry in data:
        player = Player(entry["name"])
        player.scores = entry["scores"]
        players[player.name] = player
    return players


mira = Player("Mira")
mira.scores.append({"value": 40, "date": "2026-09-26 15:00"})
save_all("scores_check.json", {"Mira": mira})
loaded = load_all("scores_check.json")
print("Loaded score:", loaded["Mira"].scores[0]["value"])
os.remove("scores_check.json")

print("---")
print("If the loaded score is 40, this lesson worked.")
print("Next file: 04_your_turn.py")
