# WEEK 5 · FINISHED APP · High Score Tracker
#
# Do not edit this file.
# Run it only after activities 1 to 5 print PASSED.
#
# What to do:
#   1. Run this file.
#   2. Click the terminal. Type each answer and press Enter.
#   3. Type 2, then Mira.
#   4. Type 3, then Mira, then 40.
#   5. Type 5. You should see Mira with 40.
#   6. Type 6 to quit.
#   7. Run this file again.
#   8. Type 1. Mira should still be there.
#   9. Type 3, then Mira, then -5. It should not crash.
#  10. Type 6 to quit.
#
# You are done when step 8 still shows Mira and step 9 does not crash.

import datetime
import json
import os

SAVE_FILE = "scores.json"


class Player:
    def __init__(self, name):
        self.name = name
        self.scores = []

    def add_score(self, value):
        if value <= 0:
            raise ValueError("Score must be a positive number.")
        date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        self.scores.append({"value": value, "date": date})
        print(f"{self.name} scored {value}!")

    def best_score(self):
        if len(self.scores) == 0:
            return 0
        best = self.scores[0]["value"]
        for entry in self.scores:
            if entry["value"] > best:
                best = entry["value"]
        return best

    def show_scores(self):
        if len(self.scores) == 0:
            print(self.name, "has no scores yet.")
            return
        print("---", self.name, "---")
        for entry in self.scores:
            print(" ", entry["value"], "—", entry["date"])


def save_all(players):
    data = []
    for player in players.values():
        data.append({"name": player.name, "scores": player.scores})
    with open(SAVE_FILE, "w") as file:
        json.dump(data, file, indent=2)
    print("Saved.")


def load_all():
    if not os.path.exists(SAVE_FILE):
        return {}
    with open(SAVE_FILE, "r") as file:
        data = json.load(file)
    players = {}
    for entry in data:
        player = Player(entry["name"])
        player.scores = entry["scores"]
        players[player.name] = player
    return players


def top_scorer(players):
    best_player = None
    best_value = -1
    for player in players.values():
        if player.best_score() > best_value:
            best_value = player.best_score()
            best_player = player
    return best_player


def view_all_players(players):
    if len(players) == 0:
        print("No players yet.")
        return
    print("--- All players ---")
    for player in players.values():
        print(" ", player.name, "| Best score:", player.best_score())


def add_player(players):
    name = input("Player name: ").strip()
    if name == "":
        print("Name cannot be empty.")
        return
    if name in players:
        print(name, "already exists.")
        return
    players[name] = Player(name)
    print("Added", name)


def add_score_for_player(players):
    name = input("Player name: ").strip()
    if name not in players:
        print("No player named", name)
        return
    try:
        value = int(input("Score: "))
        players[name].add_score(value)
    except ValueError as error:
        if str(error).startswith("invalid literal"):
            print("That's not a whole number.")
        else:
            print("Error:", error)


def view_player_scores(players):
    name = input("Player name: ").strip()
    if name not in players:
        print("No player named", name)
        return
    players[name].show_scores()


def show_top_scorer(players):
    if len(players) == 0:
        print("No players yet.")
        return
    winner = top_scorer(players)
    print("Top scorer:", winner.name, "with", winner.best_score())


def main():
    players = load_all()
    print("=== High Score Tracker ===")
    while True:
        print()
        print("1. View all players")
        print("2. Add a player")
        print("3. Add a score")
        print("4. View a player's scores")
        print("5. Show top scorer")
        print("6. Quit")
        choice = input("Choice: ").strip()
        if choice == "1":
            view_all_players(players)
        elif choice == "2":
            add_player(players)
            save_all(players)
        elif choice == "3":
            add_score_for_player(players)
            save_all(players)
        elif choice == "4":
            view_player_scores(players)
        elif choice == "5":
            show_top_scorer(players)
        elif choice == "6":
            print("Goodbye!")
            break
        else:
            print("Type a number from 1 to 6.")


if __name__ == "__main__":
    main()
