# WEEK 5 · ACTIVITY 5 OF 5 · LESSON
#
# You will learn:
#   A loop can find the player with the highest best_score.
#
# What to do:
#   1. Read this file from top to bottom.
#   2. Run it.
#   3. You should see the top scorer is Zed with 50.
#   4. Then open 05_your_turn.py.
#
# Do not edit this file.

class Player:
    def __init__(self, name):
        self.name = name
        self.scores = []

    def add_score(self, value):
        self.scores.append(value)

    def best_score(self):
        if len(self.scores) == 0:
            return 0
        return max(self.scores)

def top_scorer(players):
    best_player = None
    best_value = -1
    for player in players.values():
        if player.best_score() > best_value:
            best_value = player.best_score()
            best_player = player
    return best_player


players = {
    "Mira": Player("Mira"),
    "Zed": Player("Zed"),
}
players["Mira"].add_score(10)
players["Zed"].add_score(50)
winner = top_scorer(players)
print("Top scorer:", winner.name, "with", winner.best_score())

print("---")
print("If Zed wins with 50, this lesson worked.")
print("Next file: 05_your_turn.py")
